version: '3.8'

services:
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: tiagoramirez/pokeapp
    container_name: poke-app
    restart: always
    ports:
      - '${PORT}:${PORT}'
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URL=${MONGODB_URL}
      - GET_ALL_POKEMONS_LIMIT=${GET_ALL_POKEMONS_LIMIT}
      - MAX_POKEMONS=${MAX_POKEMONS}
      - POKEMON_REGION_PAGE_KANTO=${POKEMON_REGION_PAGE_KANTO}
      - POKEMON_REGION_PAGE_JOHTO=${POKEMON_REGION_PAGE_JOHTO}
      - POKEMON_REGION_PAGE_HOENN=${POKEMON_REGION_PAGE_HOENN}
      - POKEMON_REGION_PAGE_SINNOH=${POKEMON_REGION_PAGE_SINNOH}
      - POKEMON_REGION_PAGE_TESELIA=${POKEMON_REGION_PAGE_TESELIA}
      - POKEMON_REGION_PAGE_KALOS=${POKEMON_REGION_PAGE_KALOS}
      - POKEMON_REGION_PAGE_ALOLA=${POKEMON_REGION_PAGE_ALOLA}
      - POKEMON_REGION_PAGE_GALAR=${POKEMON_REGION_PAGE_GALAR}
      - POKEMON_REGION_PAGE_PALDEA=${POKEMON_REGION_PAGE_PALDEA}

  db:
    image: mongo:6-jammy
    container_name: poke-db
    restart: always
    environment:
      - MONGODB_DATABASE=nest-pokemon
    volumes:
      - ./mongo_prod:/data/db
