version: '3.8'

services:
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: tiagoramirez/pokeapp
    container_name: poke-app
    restart: always
    ports:
      - '${PORT}:${PORT}'
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URL=${MONGODB_URL}
      - GET_ALL_POKEMONS_LIMIT=${GET_ALL_POKEMONS_LIMIT}
      - SEED_LIMIT=${SEED_LIMIT}
      - LOG_ENABLED=${LOG_ENABLED}
      - MAX_POKEMONS=${MAX_POKEMONS}

  db:
    image: mongo:6-jammy
    container_name: poke-db
    restart: always
    environment:
      - MONGODB_DATABASE=nest-pokemon
    volumes:
      - ./mongo_prod:/data/db
