export const EnvConfiguration = () => ({
  port: process.env.PORT || 3000,
  environment: process.env.NODE_ENV || 'prod',
  mongodb: process.env.MONGODB_URL,
  getAllLimit: process.env.GET_ALL_POKEMONS_LIMIT || 10,
  maxPokemons: process.env.MAX_POKEMONS || 1010,
  kantoPage: process.env.POKEMON_REGION_PAGE_KANTO,
  johtoPage: process.env.POKEMON_REGION_PAGE_JOHTO,
  hoennPage: process.env.POKEMON_REGION_PAGE_HOENN,
  sinnohPage: process.env.POKEMON_REGION_PAGE_SINNOH,
  teseliaPage: process.env.POKEMON_REGION_PAGE_TESELIA,
  kalosPage: process.env.POKEMON_REGION_PAGE_KALOS,
  alolaPage: process.env.POKEMON_REGION_PAGE_ALOLA,
  galarPage: process.env.POKEMON_REGION_PAGE_GALAR,
  paldeaPage: process.env.POKEMON_REGION_PAGE_PALDEA,
});
